package share

import (
	"os"
	"strings"
	"testing"
)

func loadFixture(t *testing.T) *Conversation {
	t.Helper()
	conv, warnings, err := Load(fixtureHTML(t))
	if err != nil {
		t.Fatal(err)
	}
	if len(warnings) != 0 {
		t.Fatalf("unexpected warnings: %v", warnings)
	}
	return conv
}

func TestLoadFixture(t *testing.T) {
	conv := loadFixture(t)
	if conv.Title != "Fixture: Picnic Planning 🧺" {
		t.Errorf("title = %q", conv.Title)
	}
	if conv.DefaultModelSlug != "fixture-model" {
		t.Errorf("model = %q", conv.DefaultModelSlug)
	}
	if got := len(conv.LinearConversation); got != 15 {
		t.Errorf("linear conversation has %d nodes, want 15", got)
	}
	var refs, images int
	for _, node := range conv.LinearConversation {
		if node.Message == nil {
			continue
		}
		refs += len(node.Message.Metadata.ContentReferences)
		for _, p := range node.Message.Parts() {
			if p.Image != nil {
				images++
			}
		}
	}
	if refs != 4 {
		t.Errorf("decoded %d content references, want 4", refs)
	}
	if images != 2 {
		t.Errorf("decoded %d image parts, want 2", images)
	}
}

func TestPartsImageAlt(t *testing.T) {
	conv := loadFixture(t)
	var alts []string
	for _, node := range conv.LinearConversation {
		if node.Message == nil {
			continue
		}
		for _, p := range node.Message.Parts() {
			if p.Image != nil {
				alts = append(alts, p.Image.Alt+"|"+p.Image.FileID)
			}
		}
	}
	want := []string{
		"park.jpg|file_00000000000000000000000001",        // user upload: attachment name
		"Generated image|file_00000000000000000000000002", // tool output: share-id suffix stripped
	}
	if strings.Join(alts, ",") != strings.Join(want, ",") {
		t.Errorf("image alts = %v, want %v", alts, want)
	}
}

func TestFileID(t *testing.T) {
	for in, want := range map[string]string{
		"sediment://file_abc":                          "file_abc",
		"file-service://file-xyz":                      "file-xyz",
		"sediment://file_abc?shared_conversation_id=1": "file_abc",
	} {
		if got := FileID(in); got != want {
			t.Errorf("FileID(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestParseShareID(t *testing.T) {
	for _, in := range []string{
		"https://chatgpt.com/share/6a91b926-d198-83ed-8b82-9bce5aaf1a1e",
		"6A91B926-D198-83ED-8B82-9BCE5AAF1A1E",
	} {
		id, err := ParseShareID(in)
		if err != nil || id != "6a91b926-d198-83ed-8b82-9bce5aaf1a1e" {
			t.Errorf("ParseShareID(%q) = %q, %v", in, id, err)
		}
	}
	if _, err := ParseShareID("https://chatgpt.com/"); err == nil {
		t.Error("expected error for URL without ID")
	}
}

func TestValidateRejectsDivergentPath(t *testing.T) {
	conv := &Conversation{
		CurrentNode: "b",
		Mapping: map[string]Node{
			"a": {ID: "a", Children: []string{"b"}},
			"b": {ID: "b", Parent: "a"},
		},
		LinearConversation: []Node{{ID: "a"}},
	}
	if _, err := conv.validate(); err == nil {
		t.Error("expected error for truncated linear conversation")
	}
}

// fixtureHTML returns the synthetic share page in testdata, generated by
// testdata/generate-fixture.js with the real turbo-stream encoder.
func fixtureHTML(t *testing.T) string {
	t.Helper()
	html, err := os.ReadFile("../../testdata/share.html")
	if err != nil {
		t.Fatal(err)
	}
	return string(html)
}
