package markdown

import (
	"os"
	"strings"
	"testing"

	"github.com/haukeschnau/chatgpt-exporter/internal/share"
)

func TestSpliceReferences(t *testing.T) {
	// "\U0001F600" is a surrogate pair, which shifts JavaScript offsets relative
	// to rune offsets. The second marker has no reference and must be dropped.
	text := "\U0001F600 Gerrit is solid.\uE200cite\uE202turn0search7\uE201 More.\uE200cite\uE202turn0search9\uE201"
	refs := []share.ContentReference{
		{
			Type: "grouped_webpages", MatchedText: "\uE200cite\uE202turn0search7\uE201", StartIdx: 19, EndIdx: 38,
			Items: []share.RefSource{{Attribution: "gerrit.example", URL: "https://gerrit.example/docs?utm_source=chatgpt.com&x=1"}},
		},
		{
			Type: "sources_footnote", MatchedText: " ", StartIdx: 63, EndIdx: 64,
			Sources: []share.RefSource{{Title: "Gerrit docs", URL: "https://gerrit.example/docs"}},
		},
	}
	got, sources := spliceReferences(text, refs)
	want := "\U0001F600 Gerrit is solid. ([gerrit.example](https://gerrit.example/docs?x=1)) More."
	if got != want {
		t.Errorf("got  %q\nwant %q", got, want)
	}
	if len(sources) != 1 || sources[0].Title != "Gerrit docs" {
		t.Errorf("sources = %+v", sources)
	}
}

func TestSpliceReferencesFallsBackToSearch(t *testing.T) {
	marker := "\uE200cite\uE202turn1search2\uE201"
	refs := []share.ContentReference{{Type: "grouped_webpages", MatchedText: marker, StartIdx: 99, EndIdx: 120, Items: []share.RefSource{{Attribution: "x", URL: "https://x.test"}}}}
	got, _ := spliceReferences("A"+marker+" B", refs)
	if got != "A ([x](https://x.test)) B" {
		t.Errorf("got %q", got)
	}
}

func TestDemoteHeadings(t *testing.T) {
	in := "## Title\n```md\n# not a heading\n```\n#hashtag\n###### six"
	want := "### Title\n```md\n# not a heading\n```\n#hashtag\n###### six"
	if got := demoteHeadings(in); got != want {
		t.Errorf("got %q", got)
	}
}

func TestRenderFixture(t *testing.T) {
	conv, _, err := share.Load(fixtureHTML(t))
	if err != nil {
		t.Fatal(err)
	}
	var requested []string
	doc, warnings := Render(conv, Options{
		SourceURL: "https://chatgpt.com/share/x",
		ImageSrc: func(img share.ImagePart) string {
			requested = append(requested, img.FileID)
			if strings.HasSuffix(img.FileID, "2") {
				return "" // simulate a failed download
			}
			return "assets/" + img.FileID + ".jpg"
		},
	})
	if len(warnings) != 0 {
		t.Errorf("warnings: %v", warnings)
	}
	checks := map[string]string{
		"front matter":        "---\ntitle: \"Fixture: Picnic Planning 🧺\"\nsource: https://chatgpt.com/share/x\nmodel: fixture-model\n",
		"user image":          "## User\n\n![park.jpg](assets/file_00000000000000000000000001.jpg)\n\nPlan a picnic",
		"image placeholder":   "*[image: A picnic blanket under a tree]*",
		"demoted heading":     "\n## Picnic plan\n",
		"fenced heading kept": "```md\n# not a heading\n```",
		"single citation":     "shade. ([weather.example](https://weather.example/forecast)) Saturday",
		"grouped citation":    "dry. ([picnics.example](https://picnics.example/list), [picnics.example](https://picnics.example/blankets))",
		"sources list":        "**Sources**\n\n- [Weekend forecast](https://weather.example/forecast)\n- [Packing list](https://picnics.example/list)",
		"code message":        "```json\n{\"list\": [\"blanket\", \"fruit\"]}\n```",
		"final answer":        "Here is the drawing and the list. Enjoy! 😀",
	}
	for name, want := range checks {
		if !strings.Contains(doc, want) {
			t.Errorf("%s: output lacks %q", name, want)
		}
	}
	for name, unwanted := range map[string]string{
		"stale marker":        "turn0view9",
		"hidden marker":       "memcite",
		"delimiter":           "\uE200",
		"tracking parameter":  "utm_source",
		"preamble":            "I will check the local weather",
		"tool output":         "redacted",
		"custom instructions": "custom instructions",
	} {
		if strings.Contains(doc, unwanted) {
			t.Errorf("%s: output contains %q", name, unwanted)
		}
	}
	if got := strings.Count(doc, "\n## User\n"); got != 2 {
		t.Errorf("%d user turns, want 2", got)
	}
	if got := strings.Count(doc, "\n## ChatGPT\n"); got != 2 {
		t.Errorf("%d assistant turns, want 2", got)
	}
	if len(requested) != 2 {
		t.Errorf("image resolver called %d times, want 2", len(requested))
	}

	withThoughts, _ := Render(conv, Options{IncludeThoughts: true})
	for _, want := range []string{"> **Looking at the park**\n>\n> The photo shows", "> I will check the local weather", "*Worked for 4s*"} {
		if !strings.Contains(withThoughts, want) {
			t.Errorf("thoughts output lacks %q", want)
		}
	}
	if strings.Contains(withThoughts, "Looked at the park") {
		t.Error("empty thought should be skipped")
	}
}

// fixtureHTML returns the synthetic share page in testdata, generated by
// testdata/generate-fixture.js with the real turbo-stream encoder.
func fixtureHTML(t *testing.T) string {
	t.Helper()
	html, err := os.ReadFile("../../testdata/share.html")
	if err != nil {
		t.Fatal(err)
	}
	return string(html)
}
